### ISSUE TITLE
ImageBounds model key issue

### ISSUE THREAD

**Issue by Nagarro-Hitesh** [syte-ai/iOS-SDK#2]
Hi, 

We are integrating your framework into our project and faced this issue. 
In your ImageBounds model, you have mapped "b1" and "b2" to b1 and b2 keys respectively. 
But in your bounds response you are sending "b1" and "b0". 

Please refer "Bounds.swift" file line 17 and 18. "b0" key is not mapped which we are getting in the response from your bounds api.

Please check and update.

**Comment by aditrades** [comment]
Issue fixed.
